name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: codecoveragesample

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./App.BusinessLogic
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./Test.BusinessLogic
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./App.BusinessLogic
    - name: Build Test Project
      run: dotnet build --no-restore
      working-directory: ./Test.BusinessLogic
    - name: Test
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage"
      working-directory: ./Test.BusinessLogic
    - name: CodeCov
      uses: codecov/codecov-action@v1.5.2
